# Generated by Django 5.2.17 on 2026-08-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_drop_watcher_count"),
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="components",
            field=models.ManyToManyField(
                related_name="boards",
                through="dashboards.DashboardItem",
                to="catalog.servicecomponent",
            ),
        ),
    ]
