# Generated by Django 5.2.17 on 2026-08-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="An owner always reads a board, so this cannot be cleared. Marking another board default is what moves it.",
            ),
        ),
    ]
