# Generated by Django 5.2.17 on 2026-08-28 05:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("polling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(max_length=200, verbose_name="Provider ID"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("incident", "Incident"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("phase", models.CharField(max_length=32)),
                ("starts_at", models.DateTimeField(verbose_name="Starts")),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ends"),
                ),
                (
                    "affected_components",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="catalog.servicecomponent"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poll_run",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="polling.pollrun",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="catalog.service",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phase", models.CharField(max_length=32)),
                ("body", models.TextField()),
                ("posted_at", models.DateTimeField(verbose_name="Posted")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="status.serviceevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComponentStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (0, "Major outage"),
                            (1, "Partial outage"),
                            (2, "Degraded"),
                            (3, "Unknown"),
                            (4, "Maintenance"),
                            (5, "Operational"),
                        ]
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("provider", "Provider"),
                            ("components", "Components"),
                            ("incidents", "Incidents"),
                        ],
                        help_text="How the severity was arrived at: published by the provider, taken as the worst of the components, or derived from the open incidents.",
                        max_length=32,
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Started")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Ended"),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="catalog.servicecomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poll_run",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="polling.pollrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "component status",
                "verbose_name_plural": "component statuses",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=["severity"],
                        name="open_by_severity",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("component",),
                        name="one_open_status_per_component",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="status_ends_after_it_starts",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="serviceevent",
            constraint=models.UniqueConstraint(
                fields=("service", "external_id"), name="one_event_per_provider_id"
            ),
        ),
    ]
