# Generated by Django 5.2.17 on 2026-09-02 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_drop_watcher_count"),
        ("polling", "0002_every_service_has_a_poller"),
        ("status", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="serviceevent",
            index=models.Index(
                fields=["service", "kind", "phase"], name="events_by_service_and_kind"
            ),
        ),
    ]
