# Generated by Django 5.2.17 on 2026-08-27 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="componentstatus",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "component status",
                "verbose_name_plural": "component statuses",
            },
        ),
    ]
