# Generated by Django 5.2.17 on 2026-09-03 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_component_search_document"),
        ("polling", "0002_every_service_has_a_poller"),
        ("status", "0002_events_by_service_and_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="serviceevent",
            name="one_event_per_provider_id",
        ),
        migrations.AddField(
            model_name="eventupdate",
            name="source",
            field=models.CharField(
                choices=[("provider", "Provider"), ("system", "Statusboard")],
                db_default="provider",
                default="provider",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="serviceevent",
            name="detected_by",
            field=models.CharField(
                choices=[("provider", "Provider"), ("system", "Statusboard")],
                db_default="provider",
                default="provider",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="serviceevent",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Provider ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="serviceevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("service", "external_id"),
                name="one_event_per_provider_id",
            ),
        ),
    ]
