# Generated by Django 5.2.17 on 2026-08-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollrun",
            name="provider",
            field=models.CharField(
                choices=[
                    ("statuspage", "Atlassian Statuspage"),
                    ("instatus", "Instatus"),
                    ("betterstack", "Better Stack"),
                    ("incident_io", "incident.io"),
                    ("status_io", "status.io"),
                    ("cstate", "cState"),
                    ("salesforce", "Salesforce Trust"),
                    ("auth0", "Auth0"),
                    ("google_cloud", "Google Cloud"),
                    ("aws", "Amazon Web Services"),
                    ("azure", "Microsoft Azure"),
                    ("apple", "Apple"),
                    ("oracle", "Oracle Cloud"),
                    ("google_feed", "Google status feed"),
                    ("rss", "RSS feed"),
                ],
                max_length=32,
            ),
        ),
    ]
