# Generated by Django 5.2.17 on 2026-08-31 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalservice",
            name="watcher_count",
        ),
        migrations.RemoveField(
            model_name="service",
            name="watcher_count",
        ),
    ]
