# Generated by Django 5.2.17 on 2026-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_drop_watcher_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicecomponent",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Featured"),
        ),
        migrations.AddField(
            model_name="servicecomponent",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Featured"),
        ),
    ]
