# Generated by Django 5.2.17 on 2026-09-03 18:25

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_component_is_featured"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicecomponent",
            name="ancestor_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                editable=False,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="servicecomponent",
            name="ancestor_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                editable=False,
                size=None,
            ),
        ),
        # The column cannot start empty. `polling.reconcile` fills it,
        # and it runs only for a poller in `PollerQuerySet.active()`. A
        # service nobody tracks is never polled again, so its rows would
        # read as having no ancestor for good.
        #
        # A cycle terminates the walk on its own. Every row in one has a
        # parent, so no cycle is reachable from the roots the base term
        # selects. Those rows keep the empty default.
        migrations.RunSQL(
            sql="""
            WITH RECURSIVE tree AS (
                SELECT id, ARRAY[]::uuid[] AS ancestors
                FROM catalog_servicecomponent
                WHERE parent_id IS NULL
                UNION ALL
                SELECT child.id, tree.ancestors || tree.id
                FROM catalog_servicecomponent child
                JOIN tree ON child.parent_id = tree.id
            )
            UPDATE catalog_servicecomponent AS row
            SET ancestor_ids = tree.ancestors
            FROM tree
            WHERE tree.id = row.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="servicecomponent",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ancestor_ids"], name="components_by_ancestor"
            ),
        ),
    ]
