# Generated by Django 5.2.17 on 2026-09-03 18:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_component_ancestor_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicecomponent",
            name="search_document",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicecomponent",
            name="search_document",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        # The column cannot start null. `polling.reconcile` fills it, and
        # it runs only for a poller in `PollerQuerySet.active()`. A
        # service nobody tracks is never polled again, so its rows would
        # stay unfindable by search for good.
        #
        # `ancestor_ids` is already backfilled by 0004, so the ordered
        # walk here only joins the names it names.
        migrations.RunSQL(
            sql="""
            UPDATE catalog_servicecomponent AS c
            SET search_document =
                setweight(to_tsvector(coalesce(c.name, '')), 'A') ||
                setweight(to_tsvector(coalesce((
                    SELECT string_agg(a.name, ' ' ORDER BY u.ord)
                    FROM unnest(c.ancestor_ids) WITH ORDINALITY AS u(id, ord)
                    JOIN catalog_servicecomponent AS a ON a.id = u.id
                ), '')), 'B') ||
                setweight(to_tsvector(coalesce(s.name, '')), 'C')
            FROM catalog_service AS s
            WHERE s.id = c.service_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="servicecomponent",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_document"], name="components_by_search"
            ),
        ),
    ]
