# Generated by Django 5.2.17 on 2026-09-04 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_service_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalservice",
            name="description",
        ),
        migrations.RemoveField(
            model_name="historicalservice",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="is_featured",
        ),
    ]
