# Generated by Django 5.2.17 on 2026-09-04 06:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


def fill_from_ancestor_ids(apps, schema_editor):
    """Copy the array into the table, before the column goes.

    Migration 0004 backfilled the array with a recursive walk of
    `parent`. Reading it again here makes the two agree by
    construction. Recomputing would be a second answer to the same
    question.

    The array can name a component somebody deleted. A foreign key
    cannot, so such a step is dropped. That dangling reference is the
    defect this table removes.

    Python, not SQL, because the key defaults to `uuid.uuid7`. Postgres
    17 has no function for version 7.
    """
    ServiceComponent = apps.get_model("catalog", "ServiceComponent")
    ComponentAncestor = apps.get_model("catalog", "ComponentAncestor")
    live = set(ServiceComponent.objects.values_list("id", flat=True))
    links = [
        ComponentAncestor(
            ancestor_id=up,
            descendant_id=row_id,
            # The array reads root first, so the last step is the parent.
            depth=len(ancestors) - step,
        )
        for row_id, ancestors in ServiceComponent.objects.values_list(
            "id", "ancestor_ids"
        )
        for step, up in enumerate(ancestors)
        if up in live
    ]
    ComponentAncestor.objects.bulk_create(links, batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_drop_service_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentAncestor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-depth"],
            },
        ),
        migrations.AddField(
            model_name="componentancestor",
            name="ancestor",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendant_links",
                to="catalog.servicecomponent",
            ),
        ),
        migrations.AddField(
            model_name="componentancestor",
            name="descendant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ancestor_links",
                to="catalog.servicecomponent",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentancestor",
            constraint=models.UniqueConstraint(
                fields=("ancestor", "descendant"), name="one_link_per_component_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="componentancestor",
            constraint=models.CheckConstraint(
                condition=models.Q(("ancestor", models.F("descendant")), _negated=True),
                name="ancestry_excludes_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentancestor",
            constraint=models.CheckConstraint(
                condition=models.Q(("depth__gte", 1)),
                name="ancestry_depth_starts_at_one",
            ),
        ),
        # The read comes before the drop. The column is the only record
        # of the tree that survives a service nobody polls.
        migrations.RunPython(
            fill_from_ancestor_ids, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveIndex(
            model_name="servicecomponent",
            name="components_by_ancestor",
        ),
        migrations.RemoveField(
            model_name="historicalservicecomponent",
            name="ancestor_ids",
        ),
        migrations.RemoveField(
            model_name="servicecomponent",
            name="ancestor_ids",
        ),
    ]
