# Generated by Django 5.2.17 on 2026-09-04 06:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


def fill_from_parent(apps, schema_editor):
    """Fill the table with the walk `rebuild_ancestry` does.

    That walk defines a component's ancestry, so the table starts where
    a poll would leave it. The dropped array is not read. It kept the
    steps above a deleted component, and that is the defect this table
    removes.

    `ServiceComponent.ancestors` holds the rules the walk obeys.

    Python, not SQL, because the key defaults to `uuid.uuid7`. Postgres
    17 has no function for version 7.
    """
    ServiceComponent = apps.get_model("catalog", "ServiceComponent")
    ComponentAncestor = apps.get_model("catalog", "ComponentAncestor")
    rows = {
        row_id: (parent_id, service_id)
        for row_id, parent_id, service_id in ServiceComponent.objects.values_list(
            "id", "parent_id", "service_id"
        )
    }
    links = []
    for row_id, (parent_id, service_id) in rows.items():
        chain, seen, up = [], {row_id}, parent_id
        while up in rows and up not in seen and rows[up][1] == service_id:
            seen.add(up)
            chain.append(up)
            up = rows[up][0]
        links += [
            ComponentAncestor(ancestor_id=up, descendant_id=row_id, depth=depth)
            # The walk climbs, so the first step is the parent.
            for depth, up in enumerate(chain, start=1)
        ]
    ComponentAncestor.objects.bulk_create(links, batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_drop_service_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentAncestor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-depth"],
            },
        ),
        migrations.AddField(
            model_name="componentancestor",
            name="ancestor",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descendant_links",
                to="catalog.servicecomponent",
            ),
        ),
        migrations.AddField(
            model_name="componentancestor",
            name="descendant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ancestor_links",
                to="catalog.servicecomponent",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentancestor",
            constraint=models.UniqueConstraint(
                fields=("ancestor", "descendant"), name="one_link_per_component_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="componentancestor",
            constraint=models.CheckConstraint(
                condition=models.Q(("ancestor", models.F("descendant")), _negated=True),
                name="ancestry_excludes_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentancestor",
            constraint=models.CheckConstraint(
                condition=models.Q(("depth__gte", 1)),
                name="ancestry_depth_starts_at_one",
            ),
        ),
        migrations.RunPython(fill_from_parent, reverse_code=migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="servicecomponent",
            name="components_by_ancestor",
        ),
        migrations.RemoveField(
            model_name="historicalservicecomponent",
            name="ancestor_ids",
        ),
        migrations.RemoveField(
            model_name="servicecomponent",
            name="ancestor_ids",
        ),
    ]
