# Generated by Django 5.2.17 on 2026-09-04 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_component_ancestor_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalservicecomponent",
            name="search_document",
        ),
    ]
