# Generated by Django 5.2.17 on 2026-09-04 21:48

from django.db import migrations

# Ancestry and the search vector were copies of what `parent` and `name`
# already say. A copy goes stale, so each one needed a writer on every
# path that could move a component. A query answers both instead.


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0010_rollup_is_not_a_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentancestor",
            name="ancestor",
        ),
        migrations.RemoveField(
            model_name="componentancestor",
            name="descendant",
        ),
        migrations.RemoveIndex(
            model_name="servicecomponent",
            name="components_by_search",
        ),
        migrations.RemoveField(
            model_name="servicecomponent",
            name="search_document",
        ),
        migrations.DeleteModel(
            name="ComponentAncestor",
        ),
    ]
