# Generated by Django 5.2.17 on 2026-09-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_service_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalservice",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("import", "Imported from a status page"),
                ],
                db_default="manual",
                default="manual",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("import", "Imported from a status page"),
                ],
                db_default="manual",
                default="manual",
                max_length=32,
            ),
        ),
    ]
